"""empty message

Revision ID: 1644938e6762
Revises: 23d93cfef9ff
Create Date: 2015-12-01 17:50:48.291000

"""

# revision identifiers, used by Alembic.
revision = '1644938e6762'
down_revision = '23d93cfef9ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
