"""empty message

Revision ID: 17c86c1cf24f
Revises: 4356a212f9d0
Create Date: 2016-01-23 16:42:48.418000

"""

# revision identifiers, used by Alembic.
revision = '17c86c1cf24f'
down_revision = '4356a212f9d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
