"""empty message

Revision ID: 19f859e188b4
Revises: 1fd29cd2af34
Create Date: 2016-02-12 17:02:18.145000

"""

# revision identifiers, used by Alembic.
revision = '19f859e188b4'
down_revision = '1fd29cd2af34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('dcost', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('paid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'paid')
    op.drop_column('category', 'dcost')
    ### end Alembic commands ###
