"""empty message

Revision ID: 209c9f2b0372
Revises: 52cf817b6e3a
Create Date: 2015-11-13 19:56:28.351000

"""

# revision identifiers, used by Alembic.
revision = '209c9f2b0372'
down_revision = '52cf817b6e3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscribe_email', 'subscribe', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscribe_email', 'subscribe')
    op.drop_table('subscribe')
    ### end Alembic commands ###
