"""empty message

Revision ID: 241b124cc0f7
Revises: 382ac027aad9
Create Date: 2015-12-16 19:22:53.997000

"""

# revision identifiers, used by Alembic.
revision = '241b124cc0f7'
down_revision = '382ac027aad9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
