"""empty message

Revision ID: 25e3ba3cfa0b
Revises: 2169059bc89d
Create Date: 2015-12-15 16:51:18.143000

"""

# revision identifiers, used by Alembic.
revision = '25e3ba3cfa0b'
down_revision = '2169059bc89d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('type', sa.String(length=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'type')
    ### end Alembic commands ###
