"""empty message

Revision ID: 28cd2d65c9b8
Revises: 241b124cc0f7
Create Date: 2015-12-16 19:23:07.455000

"""

# revision identifiers, used by Alembic.
revision = '28cd2d65c9b8'
down_revision = '241b124cc0f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
