"""empty message

Revision ID: 34144a77c814
Revises: 5466fbd5f92a
Create Date: 2015-11-13 17:41:03.570000

"""

# revision identifiers, used by Alembic.
revision = '34144a77c814'
down_revision = '5466fbd5f92a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_status', 'contacts', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_status', 'contacts')
    ### end Alembic commands ###
