"""empty message

Revision ID: 37f0dc84937b
Revises: 6e7b283eaa
Create Date: 2015-12-17 16:33:55.603000

"""

# revision identifiers, used by Alembic.
revision = '37f0dc84937b'
down_revision = '6e7b283eaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
