"""empty message

Revision ID: 382ac027aad9
Revises: 25e3ba3cfa0b
Create Date: 2015-12-16 09:14:42.935000

"""

# revision identifiers, used by Alembic.
revision = '382ac027aad9'
down_revision = '25e3ba3cfa0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', u'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column(u'type', sa.VARCHAR(length=5), nullable=True))
    ### end Alembic commands ###
