"""empty message

Revision ID: 43d3992732c3
Revises: 2bd294feeaa9
Create Date: 2015-11-13 18:05:25.704000

"""

# revision identifiers, used by Alembic.
revision = '43d3992732c3'
down_revision = '2bd294feeaa9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_enquiry', 'contacts', ['enquiry'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_enquiry', 'contacts')
    ### end Alembic commands ###
