"""empty message

Revision ID: 4d30d5d8027
Revises: 34144a77c814
Create Date: 2015-11-13 17:41:35.825000

"""

# revision identifiers, used by Alembic.
revision = '4d30d5d8027'
down_revision = '34144a77c814'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('enquiry', sa.String(length=1000), nullable=True))
    op.drop_column('contacts', u'status')
    op.create_index('ix_contacts_enquiry', 'contacts', ['enquiry'], unique=False)
    op.drop_index('ix_contacts_status', 'contacts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_status', 'contacts', [u'status'], unique=False)
    op.drop_index('ix_contacts_enquiry', 'contacts')
    op.add_column('contacts', sa.Column(u'status', sa.INTEGER(), nullable=True))
    op.drop_column('contacts', 'enquiry')
    ### end Alembic commands ###
