"""empty message

Revision ID: 50cdee7c719d
Revises: 17c86c1cf24f
Create Date: 2016-02-12 12:03:16.338000

"""

# revision identifiers, used by Alembic.
revision = '50cdee7c719d'
down_revision = '17c86c1cf24f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('paid', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('prdcostice', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'prdcostice')
    op.drop_column('category', 'paid')
    ### end Alembic commands ###
