"""empty message

Revision ID: 52cf817b6e3a
Revises: 1acb93730bbc
Create Date: 2015-11-13 18:13:57.782000

"""

# revision identifiers, used by Alembic.
revision = '52cf817b6e3a'
down_revision = '1acb93730bbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
