"""empty message

Revision ID: 5466fbd5f92a
Revises: f6141e03bb
Create Date: 2015-11-13 16:25:44.496000

"""

# revision identifiers, used by Alembic.
revision = '5466fbd5f92a'
down_revision = 'f6141e03bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('answer', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_answer', 'contacts', ['answer'], unique=False)
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('ix_contacts_name', 'contacts', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_name', 'contacts')
    op.drop_index('ix_contacts_email', 'contacts')
    op.drop_index('ix_contacts_answer', 'contacts')
    op.drop_table('contacts')
    ### end Alembic commands ###
