"""empty message

Revision ID: 557b98e6c4c8
Revises: 50cdee7c719d
Create Date: 2016-02-12 12:08:02.529000

"""

# revision identifiers, used by Alembic.
revision = '557b98e6c4c8'
down_revision = '50cdee7c719d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
