"""empty message

Revision ID: 6bafb8b9a1a
Revises: 1644938e6762
Create Date: 2015-12-15 15:45:46.187000

"""

# revision identifiers, used by Alembic.
revision = '6bafb8b9a1a'
down_revision = '1644938e6762'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settingz',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('value', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settingz')
    ### end Alembic commands ###
