"""empty message

Revision ID: 6e7b283eaa
Revises: 28cd2d65c9b8
Create Date: 2015-12-17 16:31:51.801000

"""

# revision identifiers, used by Alembic.
revision = '6e7b283eaa'
down_revision = '28cd2d65c9b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', u'type')
    op.drop_column('settings', u'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column(u'description', sa.VARCHAR(length=250), nullable=True))
    op.add_column('settings', sa.Column(u'type', sa.VARCHAR(length=5), nullable=True))
    ### end Alembic commands ###
