"""empty message

Revision ID: 73328c0a333
Revises: 557b98e6c4c8
Create Date: 2016-02-12 12:35:06.789000

"""

# revision identifiers, used by Alembic.
revision = '73328c0a333'
down_revision = '557b98e6c4c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('visible', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'visible')
    ### end Alembic commands ###
