"""empty message

Revision ID: c52608b0dfa
Revises: 43d3992732c3
Create Date: 2015-11-13 18:11:09.433000

"""

# revision identifiers, used by Alembic.
revision = 'c52608b0dfa'
down_revision = '43d3992732c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('reply', sa.String(length=1000), nullable=True))
    op.drop_column('contacts', u'answer')
    op.create_index('ix_contacts_reply', 'contacts', ['reply'], unique=False)
    op.drop_index('ix_contacts_answer', 'contacts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_answer', 'contacts', [u'answer'], unique=False)
    op.drop_index('ix_contacts_reply', 'contacts')
    op.add_column('contacts', sa.Column(u'answer', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('contacts', 'reply')
    ### end Alembic commands ###
