"""empty message

Revision ID: f6141e03bb
Revises: 5708d7934d52
Create Date: 2015-11-10 10:44:08.545000

"""

# revision identifiers, used by Alembic.
revision = 'f6141e03bb'
down_revision = '5708d7934d52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'_category_old_20151110')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'_category_old_20151110',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'num', sa.INTEGER(), nullable=True),
    sa.Column(u'name', sa.VARCHAR(length=250), nullable=True),
    sa.Column(u'visible', sa.BOOLEAN(), nullable=True),
    sa.Column(u'icon', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    ### end Alembic commands ###
